name: snack_hunt
description: A food delivery application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  provider: ^6.0.5
  image_picker: ^1.0.4
  awesome_dialog: ^3.1.0
  dotted_border: ^2.1.0
  flutter_tabler_icons: ^1.2.0
  flutter_animate: ^4.2.0
  lottie: ^2.6.0
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  like_button: ^2.0.5
  flutter_rating_bar: ^4.0.1
  glassmorphism: ^3.0.0
  flutter_svg: ^2.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  jwt_decoder: ^2.0.1
  flutter_spinkit: ^5.2.0
  flutter_staggered_animations: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/logo.png
    - images/profile.jpg
    - images/risoles.jpg
    - images/food.png
    - images/drink.png
    - images/dessert.png
    - images/snack.png
    - images/corndog.jpg
    - images/mochi.jpg
    - images/boba.jpg
    - images/food.jpg
    - images/salad.png
    - images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700